console.log('javaScript challenges - HARD - JUNE 11 2024')
console.log('-----------------------------')

//Q1. show rating 
//given a rating, display a star (*) for each full rating and a full-stop (.) for each half rating 

function showRating(rating){
  
}
console.log(showRating(4.5)) //> * * * * .



//q2. sort by lowest to hightest price
// given an arrayof numbers return the prices sorted by low to high


//Q1. show rating 
//given a rating, display a star (*) for each full rating and a full-stop (.) for each half rating 

function shwRating(rating){
    //initiate an empty string
    
    
    // loops through the rounded down rating
    

    //if its not the last iteration add a space
   

    //if the number is not an integer 
 
    // add a full stop
  
    //return it 
}
console.log(shwRating(4.5)) //> * * * * .
